from . import student_service 
from . import department_service 
from . import user_service 
from . import course_service
from . import subject_service
from . import enrollment_service
from . import marks_service
from . import result_service
from . import fee_service
from . import faculty_service
from .faculty_subject_service import *
from .timetable_service import *