from .student import *
from .user import *
from .department import *
from .attendance import *
from .course import *
from .subject import *
from .enrollment import *
from .marks import *
from . import fee
from .faculty import *
from .faculty_subject import *
from .timetable import *